# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d74cfb0037712a7520270e25439275ff968e0ca468a131359dffd4998c8c922e941b6e36ed795ff5accfa3bed2958b578a64482ff7c728d340ef04de4cdb0293

test:
  secret_key_base: d29f38f8d126e818660ea85ae05c5fc35d361dc8d0eafcd7198926fb813b505cd66f31317d804f0bab142360357a54bd7a583a0d0c4642ebec5cf80f3d0374db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
